### ISSUE TITLE
Build on MBP M1 fails due to "undefined symbols"

### ISSUE THREAD

**Issue by hjtriem** [markus-perl/ffmpeg-build-script#78]
Hi,

The build on my MBP M1 with MacOS 11.1 fails, due to "undefined symbols". Did I do something wrong?

Output log:
----
hjtriem@MBP-M1-HJ ffmpeg-build-script % ./build-ffmpeg -b       
ffmpeg-build-script v1.22
=========================

Using 8 make jobs simultaneously.

building pkg-config
=======================
Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz as pkg-config-0.29.2.tar.gz
... Done
Extracted pkg-config-0.29.2.tar.gz
$ ./configure --silent --prefix=/Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/workspace --with-pc-path=/Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/workspace/lib/pkgconfig --with-internal-glib
$ make -j 8
$ make install

building lv2
=======================
Downloading https://lv2plug.in/spec/lv2-1.18.0.tar.bz2 as lv2-1.18.0.tar.bz2
... Done
Extracted lv2-1.18.0.tar.bz2
$ ./waf configure --prefix=/Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/workspace --lv2-user
$ ./waf
$ ./waf install

building waflib
=======================
Downloading https://gitlab.com/drobilla/autowaf/-/archive/cc37724b9bfa889baebd8cb10f38b8c7cab83e37/autowaf-cc37724b9bfa889baebd8cb10f38b8c7cab83e37.tar.gz as autowaf.tar.gz
... Done
Extracted autowaf.tar.gz

building serd
=======================
Downloading https://gitlab.com/drobilla/serd/-/archive/v0.30.6/serd-v0.30.6.tar.gz as serd-v0.30.6.tar.gz
... Done
Extracted serd-v0.30.6.tar.gz
$ cp -r /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Build.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/COPYING /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/ConfigSet.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Configure.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Context.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Errors.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Logs.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Node.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Options.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/README.md /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Runner.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Scripting.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Task.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/TaskGen.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Tools /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Utils.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/__init__.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/ansiterm.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/extras /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/fixpy2.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/processor.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/waf /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/serd-v0.30.6/waflib/
$ ./waf configure --prefix=/Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/workspace --static --no-shared --no-posix
$ ./waf
$ ./waf install

building pcre
=======================
Downloading https://ftp.pcre.org/pub/pcre/pcre-8.44.tar.gz as pcre-8.44.tar.gz
... Done
Extracted pcre-8.44.tar.gz
$ ./configure --prefix=/Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/workspace --disable-shared --enable-static
$ make -j 8
$ make install

building sord
=======================
Downloading https://gitlab.com/drobilla/sord/-/archive/v0.16.6/sord-v0.16.6.tar.gz as sord-v0.16.6.tar.gz
... Done
Extracted sord-v0.16.6.tar.gz
$ cp -r /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Build.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/COPYING /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/ConfigSet.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Configure.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Context.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Errors.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Logs.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Node.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Options.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/README.md /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Runner.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Scripting.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Task.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/TaskGen.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Tools /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Utils.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/__init__.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/ansiterm.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/extras /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/fixpy2.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/processor.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/waf /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/sord-v0.16.6/waflib/
$ ./waf configure --prefix=/Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/workspace CFLAGS=-I/Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/workspace/include --static --no-shared --no-utils
$ ./waf CFLAGS=-I/Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/workspace/include
$ ./waf install

building sratom
=======================
Downloading https://gitlab.com/lv2/sratom/-/archive/v0.6.6/sratom-v0.6.6.tar.gz as sratom-v0.6.6.tar.gz
... Done
Extracted sratom-v0.6.6.tar.gz
$ cp -r /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Build.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/COPYING /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/ConfigSet.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Configure.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Context.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Errors.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Logs.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Node.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Options.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/README.md /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Runner.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Scripting.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Task.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/TaskGen.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Tools /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Utils.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/__init__.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/ansiterm.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/extras /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/fixpy2.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/processor.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/waf /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/sratom-v0.6.6/waflib/
$ ./waf configure --prefix=/Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/workspace --static --no-shared
$ ./waf
$ ./waf install

building lilv
=======================
Downloading https://gitlab.com/lv2/lilv/-/archive/v0.24.10/lilv-v0.24.10.tar.gz as lilv-v0.24.10.tar.gz
... Done
Extracted lilv-v0.24.10.tar.gz
$ cp -r /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Build.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/COPYING /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/ConfigSet.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Configure.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Context.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Errors.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Logs.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Node.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Options.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/README.md /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Runner.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Scripting.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Task.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/TaskGen.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Tools /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/Utils.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/__init__.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/ansiterm.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/extras /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/fixpy2.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/processor.py /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/autowaf/waf /Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/lilv-v0.24.10/waflib/
$ ./waf configure --prefix=/Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/workspace --static --no-shared --no-utils
$ ./waf
$ ./waf install

building yasm
=======================
Downloading https://github.com/yasm/yasm/releases/download/v1.3.0/yasm-1.3.0.tar.gz as yasm-1.3.0.tar.gz
... Done
Extracted yasm-1.3.0.tar.gz
$ ./configure --prefix=/Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/workspace
$ make -j 8
$ make install

building nasm
=======================
Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.xz as nasm-2.15.05.tar.xz
... Done
Extracted nasm-2.15.05.tar.xz
$ ./configure --prefix=/Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/workspace --disable-shared --enable-static
$ make -j 8
$ make install

building zlib
=======================
Downloading https://www.zlib.net/zlib-1.2.11.tar.gz as zlib-1.2.11.tar.gz
... Done
Extracted zlib-1.2.11.tar.gz
$ ./configure --static --prefix=/Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/workspace
$ make -j 8
$ make install

building openssl
=======================
Downloading https://www.openssl.org/source/openssl-1.1.1i.tar.gz as openssl-1.1.1i.tar.gz
... Done
Extracted openssl-1.1.1i.tar.gz
$ ./configure --prefix=/Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/workspace no-shared no-asm darwin64-arm64-cc
$ make -j 8
$ make install_sw

building cmake
=======================
Downloading https://cmake.org/files/v3.18/cmake-3.18.4.tar.gz as cmake-3.18.4.tar.gz
... Done
Extracted cmake-3.18.4.tar.gz
$ ./configure --prefix=/Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/workspace --system-zlib
$ make -j 8
$ make install

building svtav1
=======================
Downloading https://github.com/AOMediaCodec/SVT-AV1/archive/v0.8.6.tar.gz as v0.8.6.tar.gz
... Done
Extracted v0.8.6.tar.gz
$ cmake -DCMAKE_INSTALL_PREFIX=/Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/workspace -DENABLE_SHARED=off -DBUILD_SHARED_LIBS=OFF ../.. -GUnix Makefiles -DCMAKE_BUILD_TYPE=Release
$ make -j 8
Scanning dependencies of target safestringlib
Scanning dependencies of target clog
Scanning dependencies of target EbVersionHeaderGen
Scanning dependencies of target COMMON_C_DEFAULT
Scanning dependencies of target FASTFEAT
[  1%] Building C object third_party/safestringlib/CMakeFiles/safestringlib.dir/__/__/dummy.c.o
[  2%] Generating version header
[  3%] Building C object third_party/cpuinfo/deps/clog/CMakeFiles/clog.dir/src/clog.c.o
Scanning dependencies of target ENCODER_C_DEFAULT
[  3%] Building C object Source/Lib/Common/C_DEFAULT/CMakeFiles/COMMON_C_DEFAULT.dir/EbBlend_a64_mask_c.c.o
[  3%] Building C object third_party/fastfeat/CMakeFiles/FASTFEAT.dir/fast.c.o
[  3%] Building C object Source/Lib/Encoder/C_DEFAULT/CMakeFiles/ENCODER_C_DEFAULT.dir/EbComputeSAD_C.c.o
Scanning dependencies of target COMMON_CODEC
[  3%] Building C object third_party/safestringlib/CMakeFiles/safestringlib.dir/safe_str_constraint.c.o
[  3%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbBitstreamUnit.c.o
[  4%] Building C object third_party/fastfeat/CMakeFiles/FASTFEAT.dir/fast_9.c.o
[  4%] Built target EbVersionHeaderGen
[  5%] Building C object Source/Lib/Common/C_DEFAULT/CMakeFiles/COMMON_C_DEFAULT.dir/EbInterPrediction_c.c.o
[  6%] Building C object Source/Lib/Common/C_DEFAULT/CMakeFiles/COMMON_C_DEFAULT.dir/EbIntraPrediction_c.c.o
[  6%] Built target clog
[  7%] Building C object third_party/safestringlib/CMakeFiles/safestringlib.dir/ignore_handler_s.c.o
Scanning dependencies of target cpuinfo
[  7%] Building C object third_party/cpuinfo/CMakeFiles/cpuinfo.dir/src/init.c.o
[  8%] Building C object Source/Lib/Encoder/C_DEFAULT/CMakeFiles/ENCODER_C_DEFAULT.dir/EbComputeVariance_C.c.o
[  8%] Building C object third_party/safestringlib/CMakeFiles/safestringlib.dir/strcpy_s.c.o
[  9%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbBlend_a64_mask.c.o
[  9%] Building C object Source/Lib/Common/C_DEFAULT/CMakeFiles/COMMON_C_DEFAULT.dir/EbPackUnPack_C.c.o
Scanning dependencies of target ENCODER_CODEC
[ 10%] Building C object third_party/cpuinfo/CMakeFiles/cpuinfo.dir/src/api.c.o
[ 10%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbAdaptiveMotionVectorPrediction.c.o
[ 11%] Building C object third_party/safestringlib/CMakeFiles/safestringlib.dir/strncpy_s.c.o
[ 11%] Built target cpuinfo
[ 11%] Building C object third_party/fastfeat/CMakeFiles/FASTFEAT.dir/nonmax.c.o
[ 12%] Building C object third_party/safestringlib/CMakeFiles/safestringlib.dir/strnlen_s.c.o
[ 13%] Building C object Source/Lib/Common/C_DEFAULT/CMakeFiles/COMMON_C_DEFAULT.dir/EbPictureOperators_C.c.o
Scanning dependencies of target ENCODER_GLOBALS
[ 13%] Building C object Source/Lib/Encoder/Globals/CMakeFiles/ENCODER_GLOBALS.dir/EbEncHandle.c.o
[ 13%] Built target safestringlib
[ 14%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbCdefProcess.c.o
[ 14%] Building C object Source/Lib/Common/C_DEFAULT/CMakeFiles/COMMON_C_DEFAULT.dir/cfl_c.c.o
[ 14%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbBlockStructures.c.o
[ 14%] Building C object Source/Lib/Encoder/C_DEFAULT/CMakeFiles/ENCODER_C_DEFAULT.dir/EncodeTxbRef_C.c.o
[ 15%] Building C object Source/Lib/Common/C_DEFAULT/CMakeFiles/COMMON_C_DEFAULT.dir/filterintra_c.c.o
[ 16%] Building C object Source/Lib/Encoder/C_DEFAULT/CMakeFiles/ENCODER_C_DEFAULT.dir/sad_av1.c.o
[ 17%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbCabacContextModel.c.o
[ 17%] Built target COMMON_C_DEFAULT
[ 18%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbCodingLoop.c.o
[ 18%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbCdef.c.o
[ 19%] Building C object Source/Lib/Encoder/C_DEFAULT/CMakeFiles/ENCODER_C_DEFAULT.dir/variance.c.o
[ 19%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbCodingUnit.c.o
[ 20%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbDeblockingCommon.c.o
[ 21%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbDeblockingFilter.c.o
[ 22%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbInterPrediction.c.o
[ 22%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbIntraPrediction.c.o
[ 22%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbDlfProcess.c.o
[ 23%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbEncCdef.c.o
[ 23%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbEncDecProcess.c.o
[ 24%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbInvTransforms.c.o
[ 24%] Built target ENCODER_GLOBALS
[ 25%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbEncDecResults.c.o
[ 25%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbLog.c.o
[ 26%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbMalloc.c.o
[ 26%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbMcp.c.o
[ 27%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbEncDecSegments.c.o
[ 28%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureBufferDesc.c.o
[ 28%] Built target ENCODER_C_DEFAULT
[ 28%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbEncDecTasks.c.o
[ 29%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureOperators.c.o
[ 30%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbEncInterPrediction.c.o
[ 30%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbEncIntraPrediction.c.o
[ 30%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbRestoration.c.o
[ 30%] Built target FASTFEAT
[ 31%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbEncWarpedMotion.c.o
[ 32%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbEncodeContext.c.o
[ 33%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbSegmentationParams.c.o
[ 33%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbEntropyCoding.c.o
[ 34%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbSystemResourceManager.c.o
[ 34%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbSuperRes.c.o
[ 34%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbThreads.c.o
[ 35%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbTime.c.o
[ 36%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbEntropyCodingProcess.c.o
[ 36%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbEntropyCodingResults.c.o
[ 37%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbUtility.c.o
[ 37%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbWarpedMotion.c.o
[ 38%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbFullLoop.c.o
[ 39%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/common_dsp_rtcd.c.o
[ 39%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbGlobalMotionEstimation.c.o
[ 39%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/convolve.c.o
[ 40%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbGlobalMotionEstimationCost.c.o
[ 41%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbInitialRateControlProcess.c.o
[ 42%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/grainSynthesis.c.o
[ 42%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbInitialRateControlReorderQueue.c.o
[ 43%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbInitialRateControlResults.c.o
[ 43%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbMdRateEstimation.c.o
[ 44%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbMeSadCalculation.c.o
[ 44%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbModeDecision.c.o
[ 45%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbModeDecisionConfigurationProcess.c.o
[ 46%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbModeDecisionProcess.c.o
[ 46%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbMotionEstimation.c.o
[ 47%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbMotionEstimationContext.c.o
[ 47%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbMotionEstimationProcess.c.o
[ 48%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbMotionEstimationResults.c.o
[ 48%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbNeighborArrays.c.o
[ 49%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbPacketizationProcess.c.o
[ 50%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbPacketizationReorderQueue.c.o
[ 50%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbPictureAnalysisProcess.c.o
[ 51%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbPictureAnalysisResults.c.o
[ 51%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbPictureControlSet.c.o
[ 52%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbPictureDecisionProcess.c.o
[ 52%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbPictureDecisionQueue.c.o
[ 53%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbPictureDecisionReorderQueue.c.o
[ 54%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbPictureDecisionResults.c.o
[ 54%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbPictureDemuxResults.c.o
[ 55%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbPictureManagerProcess.c.o
[ 55%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbPictureManagerQueue.c.o
[ 56%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbPictureManagerReorderQueue.c.o
[ 56%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbPredictionStructure.c.o
[ 57%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbProductCodingLoop.c.o
[ 58%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbPsnr.c.o
[ 58%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbRateControlProcess.c.o
[ 58%] Built target COMMON_CODEC
[ 59%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbRateControlResults.c.o
[ 59%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbRateControlTables.c.o
[ 60%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbRateControlTasks.c.o
Scanning dependencies of target SvtAv1Dec
[ 61%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecBitstream.c.o
[ 62%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbRateDistortionCost.c.o
[ 63%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecBitstreamUnit.c.o
[ 63%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecCdef.c.o
[ 64%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecHandle.c.o
[ 64%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbReferenceObject.c.o
[ 64%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecInterPrediction.c.o
[ 65%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecIntraPrediction.c.o
[ 66%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecInverseQuantize.c.o
[ 67%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbResize.c.o
[ 67%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbResourceCoordinationProcess.c.o
[ 68%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbResourceCoordinationResults.c.o
[ 68%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbRestProcess.c.o
[ 68%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecLF.c.o
[ 69%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecMemInit.c.o
[ 69%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecNbr.c.o
[ 70%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbRestorationPick.c.o
[ 71%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecObmc.c.o
[ 71%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecParseBlock.c.o
[ 72%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecParseFrame.c.o
[ 73%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbSegmentation.c.o
[ 74%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecParseHelper.c.o
[ 74%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecParseInterBlock.c.o
[ 74%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbSequenceControlSet.c.o
[ 75%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbSourceBasedOperationsProcess.c.o
[ 75%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbTemporalFiltering.c.o
[ 76%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbTransQuantBuffers.c.o
[ 76%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/EbTransforms.c.o
[ 77%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/aom_dsp_rtcd.c.o
[ 78%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/av1me.c.o
[ 78%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/corner_detect.c.o
[ 79%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/corner_match.c.o
[ 80%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecParseObu.c.o
[ 80%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/dwt.c.o
[ 80%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecPicMgr.c.o
[ 81%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecProcess.c.o
[ 81%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecProcessBlock.c.o
[ 82%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/fft.c.o
[ 82%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/firstpass.c.o
[ 83%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/global_motion.c.o
/Users/hjtriem/Desktop/ffmpeg/ffmpeg-build-script/packages/v0.8.6/Source/Lib/Encoder/Codec/firstpass.c:1181:14: warning: unused variable 'src_ptr' [-Wunused-variable]
    uint8_t *src_ptr = &(input_picture_ptr->buffer_y[buffer_index]);
             ^
[ 84%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecProcessFrame.c.o
[ 85%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/hash.c.o
[ 85%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/hash_motion.c.o
[ 86%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/level.c.o
[ 86%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/mcomp.c.o
[ 87%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecRestoration.c.o
[ 88%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/noise_model.c.o
[ 88%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/noise_util.c.o
1 warning generated.
[ 89%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/palette.c.o
[ 89%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecSuperRes.c.o
[ 90%] Building C object Source/Lib/Decoder/CMakeFiles/SvtAv1Dec.dir/Codec/EbDecUtils.c.o
[ 91%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/pass2_strategy.c.o
[ 91%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/ransac.c.o
[ 92%] Building C object Source/Lib/Encoder/Codec/CMakeFiles/ENCODER_CODEC.dir/vector.c.o
[ 92%] Linking C static library ../../../../../Bin/Release/libSvtAv1Dec.a
[ 92%] Built target SvtAv1Dec
Scanning dependencies of target SvtAv1DecApp
[ 94%] Building C object Source/App/DecApp/CMakeFiles/SvtAv1DecApp.dir/EbDecAppMain.c.o
[ 94%] Building C object Source/App/DecApp/CMakeFiles/SvtAv1DecApp.dir/EbDecTime.c.o
[ 94%] Building C object Source/App/DecApp/CMakeFiles/SvtAv1DecApp.dir/EbDecParamParser.c.o
[ 95%] Building C object Source/App/DecApp/CMakeFiles/SvtAv1DecApp.dir/EbFileUtils.c.o
[ 95%] Building C object Source/App/DecApp/CMakeFiles/SvtAv1DecApp.dir/EbMD5Utility.c.o
[ 96%] Linking C executable ../../../../../Bin/Release/SvtAv1DecApp
Undefined symbols for architecture arm64:
  "_cpuinfo_arm_mach_init", referenced from:
      _cpuinfo_initialize in libSvtAv1Dec.a(init.c.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../../Bin/Release/SvtAv1DecApp] Error 1
make[1]: *** [Source/App/DecApp/CMakeFiles/SvtAv1DecApp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 96%] Built target ENCODER_CODEC
make: *** [all] Error 2

Failed to Execute make -j 8 
----

Thx,

Harm Jan

**Comment by markus-perl** [comment]
Hi @hjtriem , 

I released a new version of the script. Can you check if this version works for you?

Unfortunately, I do not own an M1 Mac, making it difficult for me to test the changes.

**Comment by hjtriem** [comment]
Hi Markus,

Complete build went fine without errors, thanks!

Regards,

Harm Jan

**Comment by markus-perl** [comment]
Great. Thanks for the feedback.

**Comment by someziggyman** [comment]
@markus-perl Looks like this issue is back with the latest version of the script..
using MacBook Air M1 2020, Monterey 12.5.1
Just FYI, had to remove this commit https://github.com/markus-perl/ffmpeg-build-script/commit/470f591269cd31514af40e2ef30db43fbb13d168 to make it go though, like mentioned here: https://github.com/markus-perl/ffmpeg-build-script/issues/144

Some final stage fails. 
Log below:
ndefined symbols for architecture arm64:
  "_SecCopyErrorMessageString", referenced from:
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
  "_SecItemExport", referenced from:
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
  "_SecTrustSettingsCopyCertificates", referenced from:
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
Undefined symbols for architecture arm64:
  "_SecCopyErrorMessageString", referenced from:
Undefined symbols for architecture arm64:
  "_SecCopyErrorMessageString", referenced from:
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
  "_SecItemExport", referenced from:
  "_SecItemExport", referenced from:
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
  "_SecTrustSettingsCopyCertificates", referenced from:
  "_SecTrustSettingsCopyCertificates", referenced from:
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ffplay_g] Error 1
make: *** Waiting for unfinished jobs....
ld: symbol(s) not found for architecture arm64
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ffprobe_g] Error 1
make: *** [ffmpeg_g] Error 1
rm libavfilter/metal/vf_yadif_videotoolbox.metal.air libavfilter/metal/vf_yadif_videotoolbox.metallib libavfilter/metal/vf_yadif_videotoolbox.metallib.c

**Comment by jamauai** [comment]
Similar errors for me after removing the same commit:

```
Undefined symbols for architecture arm64:
  "_SecCopyErrorMessageString", referenced from:
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
  "_SecItemExport", referenced from:
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
  "_SecTrustSettingsCopyCertificates", referenced from:
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ffplay_g] Error 1
make: *** Waiting for unfinished jobs....
Undefined symbols for architecture arm64:
  "_SecCopyErrorMessageString", referenced from:
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
  "_SecItemExport", referenced from:
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
  "_SecTrustSettingsCopyCertificates", referenced from:
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ffmpeg_g] Error 1
Undefined symbols for architecture arm64:
  "_SecCopyErrorMessageString", referenced from:
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
  "_SecItemExport", referenced from:
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
  "_SecTrustSettingsCopyCertificates", referenced from:
      _gnutls_x509_trust_list_add_system_trust in libgnutls.a(certs.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ffprobe_g] Error 1

Failed to Execute make -j 10
```
